sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
env:
  global:
  - secure: TWbuZENUdPM1ZSm97w3Zya7lSTJKQzywITXvZ1WoMi2WoO+Be2JqIH4MRuq851NbAxFloLTSFcHMjaayaP2bDfBaJXMiI+gSiEt8OjO5+SPibOvPmeMp/kOQSIb2FHRB9Z0koALFiyzwMCE65elmKRQxgP1UCVHyr48m6QlBD3YgQhzkBUec9krNcf3Sn4XVn4Fa2nRA5K7wJNnAEX4OXHp/pTX6g9XemdMMEfbEQ5zvI6iw7qYF6K0Cu6soREMHrbIPDTQS0CQrh1x7PFA7SN3I6TBSrQ/8vq4687r+Dhll1nUsFBF1kQdE4qAXzve4MTD4P94SjUgxrXBMwkFOn5Zbcaa296lEqCs7rFChKjCBaDY3t8y0rCod3pK/SgXedLPTW2McKqlkcJ+k9xnsfkWWuliGgydZK8uCaOVTi8SuUWvg95MsVn2n/xxB6ZCPKCIOEJdbSPIi0dnWmsnMJHeZlyWAY0UuOQNMS5uLa1tEZX9LA2G3ty8QaRK61+EHYm5OJTODW/OFGOO3Ep7MEfxa6PX3iYTAc4RSZPEUZqxUuZdlG2ItNQqrtPn/4/MAFaTdMuOAgFrL0aMligeyBKvYM2LixYguuJqZbSQ8hF9YQuakWodKqLi3Yzld0LpUrA1wdz7q+Pa9lCcP0fxLvtIhOTEcEYn3ON9JD/tqndk=
  - secure: Wew3Uvu7oGXoK4DYoE6XRn9QGnJjWwl0r9qh8Mh/sUch2/5YkM7g2b8cEhiHaS4uPyEdtMNQWY7Zbdx5JcudA5vZUeKJGt+lqlBNB5G+2bB3tf8tihq4jZk8NOOZKIk+t87i5mmOnlPvIK2BzM+LvtR0GJu78N/+wsvYPwyLwVFsl27EUpKgsrE/JxgqUvnnQOjH1WzZhYaKw8yfob27JwWdFWJYVbWcDBczIpvH6+T2FEkBe1fKRIOE55w7FL81zFCtGkvnCb0STUzFs9BqePYgTRNQDYryJ/bHz5SmRM4B7b6HLJ+eDVP1SRMYH23RitrphtfukQ898dKY7y2gcofZZqCmuf1iYcwtg4Gb+TgS6uhJZC0tD2POO3TqITPanrej0UeC2Syl1izJhiXF3QTPO/Aa9VYBwvntfosK+xI1pNQmTl5wrsDGRJsIHSRiKt1d1gzPr8IrPKX8E0lPDqYxWhkPVIrqKzlvCLdjorSyQqTGh3GkIemimLZIbGvHn7EF1wQQSdIR5ImQnGE4MSEVPmKv+zVoNq3dhS7b0397QKNsWoMBat1Uz4gZSgve5RIUUMlE0dffyawTWZMgd+X8p7oYqF+a9HmnvJPxH2XTbLvj2SedJJjeNqSecZIsexerrm+0d3lPl3Ei4oPSZsnOXatTM43XGadBFBF5ImU=
deploy:
  provider: s3
  access_key_id: AKIAIBCVJYLTGFVDBZHQ
  secret_access_key:
    secure: EkJ5tAwbbaG71jVXplsB6sQoLk1qZB+mX6XFLb2F86ZeQZZnpG9fdi1OC3iVf02hNTgVdgIBFH3DYsx1wGHH+dhi3h/zqyF5kP7lZytrJD+QMeZX2Pk534JUL8uY8IYYKgvKkS+YZyG0Do5vgyWufMA302LOS41BrGd/akXLO2aODZm2MR3DhwIbpFqrYGrL4wZZhc6ltAvvkQYJNJP7jUndS7LRlLs0lYuPbkhlSwO/5M18rZvsJ/7cXyBRR8HWCpCbHLocHoRXWkLOYhkbyS9joEaccva5n/7VyjAkCdR7b3wMhjuxlTqetHTavt6emCQhJiiHx1MB53KR+W6s1k4HxRg3vx2/DK0qSvI6a9flmR63zFhaELX2ZqnPQH1X+q4Q0Iq1dWLUxSmAXTOOXeXyAbSrZoeTaO4l+72tLje9UJBP2fHdyRQ/VcJvwt5H5BhOIOuAO/+KgZCGT+xvYspYO4L6W0o/cJQEiNriPSSYLK8WG/zb9ckc6bIlQ/hAVj+DQoPa4IPfD7IGuyfOO/iFC7boqlcBkO4yJG8i+qy2BN90hLYxsrjkueOhilZDpWHnIYh+hsTwXFWCI1MeytaUEYepXN78/tK1q+6pomEwVSUPEM3wfdyy4pV4w15DRbZUJ6TIuPYRip5EWI9KUrFvSVymQ8oR3I/IJxA0fog=
  bucket: hamblinparks
  acl: ''
  on:
    repo: ksfarmer/hamblinparks
